### ISSUE TITLE
License

### ISSUE THREAD

**Issue by spotlesscoder** [jhipster/jhipster-sample-app-nodejs#14]
Hi, 

could you please add an OSS license to the repo?

Thanks :)

**Comment by jdubois** [comment]
Sorry but no, this is automatically generated by JHipster, and the generated project has no license on purpose.

While JHipster is fully OSS, and we would love all projects to be OSS, we're not forcing anyone to do so: the generated code is yours, and you do whatever you want with it.

-> Once you generate a project, it's yours, and it's up to you to make it OSS or not
